import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ANCHOR_COMPANIES } from "../prisma/seed/anchor-companies";

/*
  Downloads a logo for each of the forty real companies in the seed.

  Run it once with `pnpm logos:fetch`; the files are committed, so a fresh
  clone and a fresh seed never touch the network. A company whose logo fails
  to download simply keeps its initials on the map — the pin renderer already
  falls back, so a missing file is a cosmetic loss and nothing more.

  The demo-data disclaimer in the README covers these: they are third-party
  trademarks shown to illustrate the product, not assets we own.
*/

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, "../../../apps/web/public/company-logos");

/* Google returns the site's own icon at its native size, which beats a 32px favicon. */
const source = (domain: string) => `https://www.google.com/s2/favicons?domain=${domain}&sz=256`;

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const results = await Promise.all(
    ANCHOR_COMPANIES.map(async (company) => {
      const domain = new URL(company.website).hostname.replace(/^www\./, "");
      try {
        const response = await fetch(source(domain));
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const bytes = Buffer.from(await response.arrayBuffer());
        // Anything this small is the generic globe placeholder, not a real logo.
        if (bytes.byteLength < 300) throw new Error("placeholder icon");
        await writeFile(join(OUT_DIR, `${company.slug}.png`), bytes);
        return { slug: company.slug, bytes: bytes.byteLength, ok: true };
      } catch (error) {
        return { slug: company.slug, ok: false, why: (error as Error).message };
      }
    }),
  );

  for (const result of results) {
    const line = result.ok ? `ok    ${result.bytes} bytes` : `skip  ${result.why}`;
    console.log(`${result.slug.padEnd(16)} ${line}`);
  }

  /*
    The seed reads this list rather than guessing. Pointing a company at a logo
    we never managed to download would cost every visitor a 404 for a pin that
    was going to draw its initials anyway.
  */
  const written = results.filter((result) => result.ok).map((result) => result.slug);
  await writeFile(
    join(HERE, "../prisma/seed/company-logos.generated.ts"),
    [
      "/* Generated by scripts/fetch-logos.ts. Do not edit by hand. */",
      "",
      "export const COMPANIES_WITH_LOGOS = new Set([",
      ...written.map((slug) => `  "${slug}",`),
      "]);",
      "",
    ].join("\n"),
  );

  const failed = results.length - written.length;
  console.log(`\n${written.length} logos written, ${failed} skipped.`);
}

await main();
