/* Seeded companies, shown as names rather than logos so nothing is misused. */
export const ANCHOR_NAMES = [
  "Razorpay",
  "CRED",
  "Zerodha",
  "Swiggy",
  "Zepto",
  "Groww",
  "Meesho",
  "Postman",
  "Zoho",
  "Freshworks",
  "PhonePe",
  "Cars24",
  "Porter",
  "Slice",
  "Rapido",
  "Unacademy",
  "Ather Energy",
  "Lenskart",
  "boAt",
  "Dream11",
  "Cult.fit",
  "ShareChat",
  "Delhivery",
  "Zomato",
  "Blinkit",
  "Urban Company",
  "Juspay",
  "Chargebee",
  "BrowserStack",
  "Hasura",
  "Sarvam AI",
  "Zetwerk",
  "Darwinbox",
  "Whatfix",
];
