/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapRouteImport } from './routes/map'
import { Route as SubmitCompanyRouteImport } from './routes/submit-company'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as SettingsResumesRouteImport } from './routes/settings.resumes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitCompanyRoute = SubmitCompanyRouteImport.update({
  id: '/submit-company',
  path: '/submit-company',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsResumesRoute = SettingsResumesRouteImport.update({
  id: '/settings/resumes',
  path: '/settings/resumes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/submit-company': typeof SubmitCompanyRoute
  '/tracker': typeof TrackerRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/settings/resumes': typeof SettingsResumesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/submit-company': typeof SubmitCompanyRoute
  '/tracker': typeof TrackerRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/settings/resumes': typeof SettingsResumesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/submit-company': typeof SubmitCompanyRoute
  '/tracker': typeof TrackerRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/settings/resumes': typeof SettingsResumesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/submit-company'
    | '/tracker'
    | '/admin/submissions'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/companies/$slug'
    | '/jobs/$jobId'
    | '/settings/resumes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/submit-company'
    | '/tracker'
    | '/admin/submissions'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/companies/$slug'
    | '/jobs/$jobId'
    | '/settings/resumes'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/submit-company'
    | '/tracker'
    | '/admin/submissions'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/companies/$slug'
    | '/jobs/$jobId'
    | '/settings/resumes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  SubmitCompanyRoute: typeof SubmitCompanyRoute
  TrackerRoute: typeof TrackerRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  SettingsResumesRoute: typeof SettingsResumesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-company': {
      id: '/submit-company'
      path: '/submit-company'
      fullPath: '/submit-company'
      preLoaderRoute: typeof SubmitCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/resumes': {
      id: '/settings/resumes'
      path: '/settings/resumes'
      fullPath: '/settings/resumes'
      preLoaderRoute: typeof SettingsResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  SubmitCompanyRoute: SubmitCompanyRoute,
  TrackerRoute: TrackerRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  SettingsResumesRoute: SettingsResumesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
