import type { FundingStage } from "@prisma/client";

/*
  Forty companies people will recognise, so the map reads as a real place
  rather than lorem ipsum. Figures are public and approximate — the README
  says plainly that this is demo data, not a live listings feed.

  hqCity/hqArea must match an entry in localities.ts.
*/

export type AnchorCompany = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  website: string;
  industries: string[];
  foundedYear: number;
  employeeCount: number;
  fundingStage: FundingStage;
  totalFundingUsd: number | null;
  valuationUsd: number | null;
  hqCity: string;
  hqArea: string;
  extraOffices?: { city: string; area: string }[];
  founders: { name: string; title: string }[];
};

export const ANCHOR_COMPANIES: readonly AnchorCompany[] = [
  {
    slug: "razorpay",
    name: "Razorpay",
    tagline: "Payments and banking for Indian businesses",
    description:
      "Razorpay builds the payments stack most Indian internet businesses run on — a payment gateway, a neobanking suite for payroll and vendor payouts, and lending products for merchants.",
    website: "https://razorpay.com",
    industries: ["Fintech", "SaaS", "Enterprise Software"],
    foundedYear: 2014,
    employeeCount: 3000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 741_000_000,
    valuationUsd: 7_500_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    extraOffices: [{ city: "Bengaluru", area: "Bellandur" }],
    founders: [
      { name: "Harshil Mathur", title: "Co-founder & CEO" },
      { name: "Shashank Kumar", title: "Co-founder & Managing Director" },
    ],
  },
  {
    slug: "cred",
    name: "CRED",
    tagline: "A rewards club for creditworthy India",
    description:
      "CRED started as a credit card bill payment app that paid members in rewards and grew into a members-only commerce, lending, and payments product aimed at high-trust consumers.",
    website: "https://cred.club",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2018,
    employeeCount: 800,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_000_000_000,
    valuationUsd: 6_400_000_000,
    hqCity: "Bengaluru",
    hqArea: "Indiranagar",
    founders: [{ name: "Kunal Shah", title: "Founder & CEO" }],
  },
  {
    slug: "zerodha",
    name: "Zerodha",
    tagline: "India's largest retail stockbroker, built without ads",
    description:
      "Zerodha runs the Kite trading platform and is India's biggest retail brokerage by active clients. It is famously bootstrapped and profitable, and has never raised outside capital.",
    website: "https://zerodha.com",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2010,
    employeeCount: 1200,
    fundingStage: "BOOTSTRAPPED",
    totalFundingUsd: null,
    valuationUsd: 3_600_000_000,
    hqCity: "Bengaluru",
    hqArea: "JP Nagar",
    founders: [
      { name: "Nithin Kamath", title: "Co-founder & CEO" },
      { name: "Nikhil Kamath", title: "Co-founder" },
    ],
  },
  {
    slug: "swiggy",
    name: "Swiggy",
    tagline: "Food, groceries, and everything else, delivered",
    description:
      "Swiggy runs food delivery, the Instamart quick-commerce business, and Dineout restaurant bookings across hundreds of Indian cities.",
    website: "https://www.swiggy.com",
    industries: ["Consumer", "Logistics", "Marketplace"],
    foundedYear: 2014,
    employeeCount: 5500,
    fundingStage: "PUBLIC",
    totalFundingUsd: 3_600_000_000,
    valuationUsd: 11_000_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    extraOffices: [
      { city: "Gurugram", area: "Cyber City" },
      { city: "Mumbai", area: "Andheri East" },
    ],
    founders: [
      { name: "Sriharsha Majety", title: "Co-founder & CEO" },
      { name: "Nandan Reddy", title: "Co-founder" },
      { name: "Rahul Jaimini", title: "Co-founder" },
    ],
  },
  {
    slug: "zepto",
    name: "Zepto",
    tagline: "Groceries in ten minutes",
    description:
      "Zepto runs a dark-store network that promises grocery delivery in about ten minutes, expanding into a broader quick-commerce catalogue and a café business.",
    website: "https://www.zeptonow.com",
    industries: ["E-commerce", "Logistics", "Consumer"],
    foundedYear: 2021,
    employeeCount: 2500,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_950_000_000,
    valuationUsd: 5_000_000_000,
    hqCity: "Mumbai",
    hqArea: "Powai",
    extraOffices: [{ city: "Bengaluru", area: "Bellandur" }],
    founders: [
      { name: "Aadit Palicha", title: "Co-founder & CEO" },
      { name: "Kaivalya Vohra", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "groww",
    name: "Groww",
    tagline: "Investing made simple for first-time investors",
    description:
      "Groww is a retail investment platform covering mutual funds, stocks, derivatives, and fixed deposits, built for people making their first investment.",
    website: "https://groww.in",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2016,
    employeeCount: 1400,
    fundingStage: "PUBLIC",
    totalFundingUsd: 393_000_000,
    valuationUsd: 6_800_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    founders: [
      { name: "Lalit Keshre", title: "Co-founder & CEO" },
      { name: "Harsh Jain", title: "Co-founder" },
      { name: "Ishan Bansal", title: "Co-founder" },
      { name: "Neeraj Singh", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "meesho",
    name: "Meesho",
    tagline: "E-commerce for the next 500 million shoppers",
    description:
      "Meesho is a zero-commission marketplace built around small sellers and value-conscious buyers in tier-2 and tier-3 India.",
    website: "https://www.meesho.com",
    industries: ["E-commerce", "Marketplace", "Consumer"],
    foundedYear: 2015,
    employeeCount: 1800,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_360_000_000,
    valuationUsd: 4_900_000_000,
    hqCity: "Bengaluru",
    hqArea: "HSR Layout",
    founders: [
      { name: "Vidit Aatrey", title: "Co-founder & CEO" },
      { name: "Sanjeev Barnwal", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "postman",
    name: "Postman",
    tagline: "The API platform developers actually open every day",
    description:
      "Postman is an API development platform used by millions of developers for designing, testing, documenting, and monitoring APIs.",
    website: "https://www.postman.com",
    industries: ["Developer Tools", "SaaS", "Enterprise Software"],
    foundedYear: 2014,
    employeeCount: 900,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 433_000_000,
    valuationUsd: 5_600_000_000,
    hqCity: "Bengaluru",
    hqArea: "Indiranagar",
    extraOffices: [{ city: "San Francisco", area: "SoMa" }],
    founders: [
      { name: "Abhinav Asthana", title: "Co-founder & CEO" },
      { name: "Ankit Sobti", title: "Co-founder & CTO" },
      { name: "Abhijit Kane", title: "Co-founder" },
    ],
  },
  {
    slug: "zoho",
    name: "Zoho",
    tagline: "A whole software suite, built far from the city",
    description:
      "Zoho makes more than fifty business applications spanning CRM, finance, HR, and collaboration, and is known for staying private, profitable, and rural-first.",
    website: "https://www.zoho.com",
    industries: ["SaaS", "Enterprise Software"],
    foundedYear: 1996,
    employeeCount: 15000,
    fundingStage: "BOOTSTRAPPED",
    totalFundingUsd: null,
    valuationUsd: null,
    hqCity: "Chennai",
    hqArea: "Guindy",
    extraOffices: [{ city: "Chennai", area: "Perungudi (OMR)" }],
    founders: [
      { name: "Sridhar Vembu", title: "Co-founder & Chief Scientist" },
      { name: "Tony Thomas", title: "Co-founder" },
    ],
  },
  {
    slug: "freshworks",
    name: "Freshworks",
    tagline: "Customer and employee software that is quick to deploy",
    description:
      "Freshworks sells customer support, IT service management, and CRM software to mid-market businesses, and was the first Indian SaaS company to list on Nasdaq.",
    website: "https://www.freshworks.com",
    industries: ["SaaS", "Enterprise Software"],
    foundedYear: 2010,
    employeeCount: 5000,
    fundingStage: "PUBLIC",
    totalFundingUsd: 484_000_000,
    valuationUsd: 4_200_000_000,
    hqCity: "Chennai",
    hqArea: "Perungudi (OMR)",
    extraOffices: [{ city: "Bengaluru", area: "Whitefield" }],
    founders: [
      { name: "Girish Mathrubootham", title: "Founder & Executive Chairman" },
      { name: "Shan Krishnasamy", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "phonepe",
    name: "PhonePe",
    tagline: "UPI payments at national scale",
    description:
      "PhonePe processes a large share of India's UPI transactions and has expanded into insurance distribution, wealth products, and the Indus app store.",
    website: "https://www.phonepe.com",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2015,
    employeeCount: 5000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_500_000_000,
    valuationUsd: 12_000_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    founders: [
      { name: "Sameer Nigam", title: "Co-founder & CEO" },
      { name: "Rahul Chari", title: "Co-founder & CTO" },
      { name: "Burzin Engineer", title: "Co-founder" },
    ],
  },
  {
    slug: "cars24",
    name: "Cars24",
    tagline: "Buying and selling used cars without the haggling",
    description:
      "Cars24 runs an end-to-end used-car marketplace covering inspection, pricing, financing, and transfer paperwork.",
    website: "https://www.cars24.com",
    industries: ["Marketplace", "Mobility", "Fintech"],
    foundedYear: 2015,
    employeeCount: 3500,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_300_000_000,
    valuationUsd: 3_300_000_000,
    hqCity: "Gurugram",
    hqArea: "Udyog Vihar",
    founders: [
      { name: "Vikram Chopra", title: "Co-founder & CEO" },
      { name: "Mehul Agrawal", title: "Co-founder" },
      { name: "Ruchit Agarwal", title: "Co-founder & CFO" },
    ],
  },
  {
    slug: "porter",
    name: "Porter",
    tagline: "Intracity logistics on demand",
    description:
      "Porter matches businesses and individuals with mini-trucks, two-wheelers, and packers for same-day intracity deliveries.",
    website: "https://porter.in",
    industries: ["Logistics", "Marketplace", "Mobility"],
    foundedYear: 2014,
    employeeCount: 1500,
    fundingStage: "SERIES_C",
    totalFundingUsd: 250_000_000,
    valuationUsd: 1_200_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    founders: [
      { name: "Pranav Goel", title: "Co-founder & CEO" },
      { name: "Uttam Digga", title: "Co-founder & COO" },
      { name: "Vikas Choudhary", title: "Co-founder" },
    ],
  },
  {
    slug: "jar",
    name: "Jar",
    tagline: "Save spare change in digital gold",
    description:
      "Jar rounds up everyday spends and invests the change in digital gold, aiming at first-time savers who have never held a formal investment product.",
    website: "https://www.myjar.app",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2021,
    employeeCount: 300,
    fundingStage: "SERIES_B",
    totalFundingUsd: 58_000_000,
    valuationUsd: 300_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    founders: [
      { name: "Nishchay AG", title: "Co-founder & CEO" },
      { name: "Misbah Ashraf", title: "Co-founder" },
    ],
  },
  {
    slug: "slice",
    name: "Slice",
    tagline: "Banking and credit designed for young India",
    description:
      "Slice began as a credit card alternative for young professionals and now operates as a merged small finance bank offering UPI, deposits, and credit.",
    website: "https://www.sliceit.com",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2016,
    employeeCount: 900,
    fundingStage: "SERIES_C",
    totalFundingUsd: 340_000_000,
    valuationUsd: 1_500_000_000,
    hqCity: "Bengaluru",
    hqArea: "HSR Layout",
    founders: [{ name: "Rajan Bajaj", title: "Founder & CEO" }],
  },
  {
    slug: "rapido",
    name: "Rapido",
    tagline: "Bike taxis for the last five kilometres",
    description:
      "Rapido runs India's largest bike-taxi network alongside auto and cab services, focused on short intracity trips.",
    website: "https://rapido.bike",
    industries: ["Mobility", "Marketplace", "Consumer"],
    foundedYear: 2015,
    employeeCount: 2000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 500_000_000,
    valuationUsd: 1_100_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    extraOffices: [{ city: "Hyderabad", area: "Gachibowli" }],
    founders: [
      { name: "Pavan Guntupalli", title: "Co-founder & CEO" },
      { name: "Aravind Sanka", title: "Co-founder" },
      { name: "Rishikesh SR", title: "Co-founder" },
    ],
  },
  {
    slug: "unacademy",
    name: "Unacademy",
    tagline: "Live classes for competitive exams",
    description:
      "Unacademy runs live online classes for exam preparation, from UPSC and JEE to state-level tests, alongside offline centres.",
    website: "https://unacademy.com",
    industries: ["Edtech", "Consumer"],
    foundedYear: 2015,
    employeeCount: 3000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 880_000_000,
    valuationUsd: 3_400_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    founders: [
      { name: "Gaurav Munjal", title: "Co-founder & CEO" },
      { name: "Roman Saini", title: "Co-founder" },
      { name: "Hemesh Singh", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "ather-energy",
    name: "Ather Energy",
    tagline: "Electric scooters designed from scratch in India",
    description:
      "Ather designs and manufactures electric two-wheelers and runs the Ather Grid fast-charging network across Indian cities.",
    website: "https://www.atherenergy.com",
    industries: ["Mobility", "Climate", "Consumer"],
    foundedYear: 2013,
    employeeCount: 2500,
    fundingStage: "PUBLIC",
    totalFundingUsd: 700_000_000,
    valuationUsd: 1_800_000_000,
    hqCity: "Bengaluru",
    hqArea: "Whitefield",
    founders: [
      { name: "Tarun Mehta", title: "Co-founder & CEO" },
      { name: "Swapnil Jain", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "lenskart",
    name: "Lenskart",
    tagline: "Eyewear, online and on the high street",
    description:
      "Lenskart sells prescription glasses, sunglasses, and lenses through an omnichannel model backed by its own manufacturing and robotic lens fitting.",
    website: "https://www.lenskart.com",
    industries: ["D2C", "E-commerce", "Healthtech"],
    foundedYear: 2010,
    employeeCount: 8000,
    fundingStage: "PUBLIC",
    totalFundingUsd: 1_800_000_000,
    valuationUsd: 8_000_000_000,
    hqCity: "Gurugram",
    hqArea: "Cyber City",
    extraOffices: [{ city: "Bengaluru", area: "Whitefield" }],
    founders: [
      { name: "Peyush Bansal", title: "Founder & CEO" },
      { name: "Amit Chaudhary", title: "Co-founder" },
      { name: "Sumeet Kapahi", title: "Co-founder" },
    ],
  },
  {
    slug: "boat",
    name: "boAt",
    tagline: "Audio and wearables for everyday India",
    description:
      "boAt sells earphones, smartwatches, and speakers, and became one of India's largest consumer audio brands through aggressive online distribution.",
    website: "https://www.boat-lifestyle.com",
    industries: ["D2C", "Consumer", "E-commerce"],
    foundedYear: 2016,
    employeeCount: 700,
    fundingStage: "SERIES_C",
    totalFundingUsd: 160_000_000,
    valuationUsd: 1_400_000_000,
    hqCity: "Mumbai",
    hqArea: "Andheri East",
    founders: [
      { name: "Sameer Mehta", title: "Co-founder & CEO" },
      { name: "Aman Gupta", title: "Co-founder & CMO" },
    ],
  },
  {
    slug: "dream11",
    name: "Dream11",
    tagline: "Fantasy sports for a cricket-mad country",
    description:
      "Dream11 runs India's largest fantasy sports platform, with cricket, football, and kabaddi contests played by well over a hundred million users.",
    website: "https://www.dream11.com",
    industries: ["Gaming", "Consumer"],
    foundedYear: 2008,
    employeeCount: 900,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_300_000_000,
    valuationUsd: 8_000_000_000,
    hqCity: "Mumbai",
    hqArea: "Lower Parel",
    founders: [
      { name: "Harsh Jain", title: "Co-founder & CEO" },
      { name: "Bhavit Sheth", title: "Co-founder & COO" },
    ],
  },
  {
    slug: "vedantu",
    name: "Vedantu",
    tagline: "Live tutoring for school students",
    description:
      "Vedantu runs interactive live classes for school curricula and competitive exam preparation, with an emphasis on small-batch teaching.",
    website: "https://www.vedantu.com",
    industries: ["Edtech", "Consumer"],
    foundedYear: 2014,
    employeeCount: 1200,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 300_000_000,
    valuationUsd: 600_000_000,
    hqCity: "Bengaluru",
    hqArea: "HSR Layout",
    founders: [
      { name: "Vamsi Krishna", title: "Co-founder & CEO" },
      { name: "Pulkit Jain", title: "Co-founder" },
      { name: "Anand Prakash", title: "Co-founder" },
    ],
  },
  {
    slug: "cult-fit",
    name: "Cult.fit",
    tagline: "Gyms, classes, and everything fitness",
    description:
      "Cult.fit runs fitness centres, group classes, and an at-home workout app, alongside mental wellness and nutrition products.",
    website: "https://www.cult.fit",
    industries: ["Healthtech", "Consumer"],
    foundedYear: 2016,
    employeeCount: 3000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 800_000_000,
    valuationUsd: 1_600_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    founders: [
      { name: "Mukesh Bansal", title: "Co-founder" },
      { name: "Ankit Nagori", title: "Co-founder" },
    ],
  },
  {
    slug: "sharechat",
    name: "ShareChat",
    tagline: "Social media in fifteen Indian languages",
    description:
      "ShareChat runs a regional-language social network and the Moj short-video app, serving users who post and scroll in languages other than English.",
    website: "https://sharechat.com",
    industries: ["Consumer", "AI"],
    foundedYear: 2015,
    employeeCount: 1000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_700_000_000,
    valuationUsd: 2_000_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    founders: [
      { name: "Ankush Sachdeva", title: "Co-founder & CEO" },
      { name: "Bhanu Pratap Singh", title: "Co-founder & CTO" },
      { name: "Farid Ahsan", title: "Co-founder & COO" },
    ],
  },
  {
    slug: "paytm",
    name: "Paytm",
    tagline: "Payments, commerce, and financial services",
    description:
      "Paytm operates a wallet, UPI payments, merchant QR and device business, and distributes lending and wealth products.",
    website: "https://paytm.com",
    industries: ["Fintech", "Consumer", "Marketplace"],
    foundedYear: 2010,
    employeeCount: 10000,
    fundingStage: "PUBLIC",
    totalFundingUsd: 4_800_000_000,
    valuationUsd: 5_000_000_000,
    hqCity: "Noida",
    hqArea: "Sector 62",
    founders: [{ name: "Vijay Shekhar Sharma", title: "Founder & CEO" }],
  },
  {
    slug: "delhivery",
    name: "Delhivery",
    tagline: "Supply chain infrastructure for Indian commerce",
    description:
      "Delhivery runs express parcel delivery, freight, warehousing, and cross-border logistics with a large automated sortation network.",
    website: "https://www.delhivery.com",
    industries: ["Logistics", "Enterprise Software"],
    foundedYear: 2011,
    employeeCount: 60000,
    fundingStage: "PUBLIC",
    totalFundingUsd: 1_300_000_000,
    valuationUsd: 3_000_000_000,
    hqCity: "Gurugram",
    hqArea: "Cyber City",
    founders: [
      { name: "Sahil Barua", title: "Co-founder & CEO" },
      { name: "Mohit Tandon", title: "Co-founder" },
      { name: "Bhavesh Manglani", title: "Co-founder" },
      { name: "Suraj Saharan", title: "Co-founder" },
    ],
  },
  {
    slug: "zomato",
    name: "Zomato",
    tagline: "Restaurant discovery and food delivery",
    description:
      "Zomato covers restaurant listings, food delivery, dining-out bookings, and the Hyperpure supplies business for restaurants.",
    website: "https://www.zomato.com",
    industries: ["Consumer", "Marketplace", "Logistics"],
    foundedYear: 2008,
    employeeCount: 5000,
    fundingStage: "PUBLIC",
    totalFundingUsd: 2_100_000_000,
    valuationUsd: 25_000_000_000,
    hqCity: "Gurugram",
    hqArea: "Golf Course Road",
    founders: [
      { name: "Deepinder Goyal", title: "Co-founder & CEO" },
      { name: "Pankaj Chaddah", title: "Co-founder" },
    ],
  },
  {
    slug: "blinkit",
    name: "Blinkit",
    tagline: "Groceries and essentials in minutes",
    description:
      "Blinkit runs a dense dark-store network for ten-minute delivery of groceries, electronics, and household essentials.",
    website: "https://blinkit.com",
    industries: ["E-commerce", "Logistics", "Consumer"],
    foundedYear: 2013,
    employeeCount: 2500,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 690_000_000,
    valuationUsd: 13_000_000_000,
    hqCity: "Gurugram",
    hqArea: "Udyog Vihar",
    founders: [{ name: "Albinder Dhindsa", title: "Co-founder & CEO" }],
  },
  {
    slug: "urban-company",
    name: "Urban Company",
    tagline: "Trained professionals for home services",
    description:
      "Urban Company matches customers with vetted professionals for salon services, appliance repair, cleaning, and painting, and trains its partner network.",
    website: "https://www.urbancompany.com",
    industries: ["Marketplace", "Consumer"],
    foundedYear: 2014,
    employeeCount: 3000,
    fundingStage: "PUBLIC",
    totalFundingUsd: 500_000_000,
    valuationUsd: 2_800_000_000,
    hqCity: "Gurugram",
    hqArea: "Cyber City",
    extraOffices: [{ city: "Dubai", area: "Internet City" }],
    founders: [
      { name: "Abhiraj Singh Bhal", title: "Co-founder & CEO" },
      { name: "Varun Khaitan", title: "Co-founder" },
      { name: "Raghav Chandra", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "pharmeasy",
    name: "PharmEasy",
    tagline: "Medicines and diagnostics delivered home",
    description:
      "PharmEasy delivers prescription and over-the-counter medicines, runs diagnostic labs, and operates a pharmacy distribution business.",
    website: "https://pharmeasy.in",
    industries: ["Healthtech", "E-commerce"],
    foundedYear: 2015,
    employeeCount: 4000,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 1_600_000_000,
    valuationUsd: 700_000_000,
    hqCity: "Mumbai",
    hqArea: "Andheri East",
    founders: [
      { name: "Siddharth Shah", title: "Co-founder & CEO" },
      { name: "Dharmil Sheth", title: "Co-founder" },
      { name: "Dhaval Shah", title: "Co-founder" },
    ],
  },
  {
    slug: "juspay",
    name: "Juspay",
    tagline: "Payment orchestration behind the checkout button",
    description:
      "Juspay builds payment orchestration and checkout infrastructure used by large merchants and banks, and maintains open-source payment tooling.",
    website: "https://juspay.io",
    industries: ["Fintech", "Developer Tools", "Enterprise Software"],
    foundedYear: 2012,
    employeeCount: 600,
    fundingStage: "SERIES_C",
    totalFundingUsd: 120_000_000,
    valuationUsd: 900_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    founders: [
      { name: "Vimal Kumar", title: "Founder & CEO" },
      { name: "Ramanathan RV", title: "Co-founder" },
    ],
  },
  {
    slug: "chargebee",
    name: "Chargebee",
    tagline: "Subscription billing and revenue operations",
    description:
      "Chargebee handles recurring billing, invoicing, revenue recognition, and retention for subscription businesses worldwide.",
    website: "https://www.chargebee.com",
    industries: ["SaaS", "Fintech", "Enterprise Software"],
    foundedYear: 2011,
    employeeCount: 1100,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 468_000_000,
    valuationUsd: 3_500_000_000,
    hqCity: "Chennai",
    hqArea: "Perungudi (OMR)",
    extraOffices: [{ city: "Bengaluru", area: "Indiranagar" }],
    founders: [
      { name: "Krish Subramanian", title: "Co-founder & CEO" },
      { name: "Rajaraman Santhanam", title: "Co-founder & COO" },
      { name: "Thiyagarajan T", title: "Co-founder" },
      { name: "Saravanan KP", title: "Co-founder" },
    ],
  },
  {
    slug: "browserstack",
    name: "BrowserStack",
    tagline: "Test on real browsers and real devices",
    description:
      "BrowserStack gives developers instant access to thousands of real browsers and mobile devices for manual and automated testing.",
    website: "https://www.browserstack.com",
    industries: ["Developer Tools", "SaaS"],
    foundedYear: 2011,
    employeeCount: 1000,
    fundingStage: "SERIES_C",
    totalFundingUsd: 250_000_000,
    valuationUsd: 4_000_000_000,
    hqCity: "Mumbai",
    hqArea: "Powai",
    extraOffices: [{ city: "Singapore", area: "Downtown Core" }],
    founders: [
      { name: "Ritesh Arora", title: "Co-founder & CEO" },
      { name: "Nakul Aggarwal", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "hasura",
    name: "Hasura",
    tagline: "Instant APIs over your data",
    description:
      "Hasura generates GraphQL and REST APIs over existing databases and services, with authorisation and caching built in.",
    website: "https://hasura.io",
    industries: ["Developer Tools", "SaaS"],
    foundedYear: 2017,
    employeeCount: 250,
    fundingStage: "SERIES_C",
    totalFundingUsd: 136_000_000,
    valuationUsd: 1_000_000_000,
    hqCity: "Bengaluru",
    hqArea: "Indiranagar",
    extraOffices: [{ city: "San Francisco", area: "SoMa" }],
    founders: [
      { name: "Tanmai Gopal", title: "Co-founder & CEO" },
      { name: "Rajoshi Ghosh", title: "Co-founder & COO" },
    ],
  },
  {
    slug: "sarvam-ai",
    name: "Sarvam AI",
    tagline: "Foundation models built for Indian languages",
    description:
      "Sarvam AI trains large language models and speech systems for Indian languages, and builds developer tooling and voice agents on top of them.",
    website: "https://www.sarvam.ai",
    industries: ["AI", "Developer Tools"],
    foundedYear: 2023,
    employeeCount: 120,
    fundingStage: "SERIES_A",
    totalFundingUsd: 41_000_000,
    valuationUsd: 300_000_000,
    hqCity: "Bengaluru",
    hqArea: "Koramangala",
    founders: [
      { name: "Vivek Raghavan", title: "Co-founder" },
      { name: "Pratyush Kumar", title: "Co-founder" },
    ],
  },
  {
    slug: "krutrim",
    name: "Krutrim",
    tagline: "An Indian AI stack, from silicon to assistant",
    description:
      "Krutrim builds multilingual large language models, cloud infrastructure, and an AI assistant aimed at Indian users and developers.",
    website: "https://www.olakrutrim.com",
    industries: ["AI", "Enterprise Software"],
    foundedYear: 2023,
    employeeCount: 300,
    fundingStage: "SERIES_B",
    totalFundingUsd: 100_000_000,
    valuationUsd: 1_000_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    founders: [{ name: "Bhavish Aggarwal", title: "Founder" }],
  },
  {
    slug: "zetwerk",
    name: "Zetwerk",
    tagline: "A manufacturing network you can order from",
    description:
      "Zetwerk connects buyers with contract manufacturers for fabrication, machining, and precision components, managing quality and delivery in between.",
    website: "https://www.zetwerk.com",
    industries: ["Marketplace", "Enterprise Software", "Logistics"],
    foundedYear: 2018,
    employeeCount: 2500,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 750_000_000,
    valuationUsd: 3_000_000_000,
    hqCity: "Bengaluru",
    hqArea: "Whitefield",
    founders: [
      { name: "Amrit Acharya", title: "Co-founder & CEO" },
      { name: "Srinath Ramakkrushnan", title: "Co-founder" },
      { name: "Rahul Sharma", title: "Co-founder" },
      { name: "Vishal Chaudhary", title: "Co-founder" },
    ],
  },
  {
    slug: "darwinbox",
    name: "Darwinbox",
    tagline: "HR software for large Asian enterprises",
    description:
      "Darwinbox is an end-to-end HR platform covering hiring, onboarding, payroll, performance, and engagement for large employers across Asia.",
    website: "https://darwinbox.com",
    industries: ["SaaS", "Enterprise Software"],
    foundedYear: 2015,
    employeeCount: 900,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 150_000_000,
    valuationUsd: 1_000_000_000,
    hqCity: "Hyderabad",
    hqArea: "HITEC City",
    extraOffices: [{ city: "Singapore", area: "Downtown Core" }],
    founders: [
      { name: "Jayant Paleti", title: "Co-founder" },
      { name: "Rohit Chennamaneni", title: "Co-founder" },
      { name: "Chaitanya Peddi", title: "Co-founder" },
    ],
  },
  {
    slug: "whatfix",
    name: "Whatfix",
    tagline: "In-app guidance so software actually gets used",
    description:
      "Whatfix layers interactive walkthroughs and analytics on top of enterprise applications so employees and customers learn them in context.",
    website: "https://whatfix.com",
    industries: ["SaaS", "Enterprise Software"],
    foundedYear: 2014,
    employeeCount: 900,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 265_000_000,
    valuationUsd: 900_000_000,
    hqCity: "Bengaluru",
    hqArea: "Bellandur",
    extraOffices: [{ city: "San Francisco", area: "SoMa" }],
    founders: [
      { name: "Khadim Batti", title: "Co-founder & CEO" },
      { name: "Vara Kumar", title: "Co-founder & CTO" },
    ],
  },
  {
    slug: "moneyview",
    name: "Moneyview",
    tagline: "Credit for people the bureaus can't score",
    description:
      "Moneyview underwrites personal loans using alternative data and runs a money-management app for borrowers with thin credit files.",
    website: "https://moneyview.in",
    industries: ["Fintech", "Consumer"],
    foundedYear: 2014,
    employeeCount: 1200,
    fundingStage: "SERIES_D_PLUS",
    totalFundingUsd: 190_000_000,
    valuationUsd: 1_200_000_000,
    hqCity: "Bengaluru",
    hqArea: "HSR Layout",
    founders: [
      { name: "Sanjay Aggarwal", title: "Co-founder & CEO" },
      { name: "Puneet Agarwal", title: "Co-founder" },
    ],
  },
];
