import type { Seniority } from "@prisma/client";

/*
  Departments, the job titles each one posts, and the investor pool.
  Weights decide how the ~1,500 jobs are split; Engineering takes about 40%
  the way it does at a real startup.
*/

export type DepartmentSeed = {
  name: string;
  slug: string;
  weight: number;
  titles: readonly string[];
};

export const DEPARTMENTS: readonly DepartmentSeed[] = [
  {
    name: "Engineering",
    slug: "engineering",
    weight: 40,
    titles: [
      "Backend Engineer",
      "Frontend Engineer",
      "Full Stack Engineer",
      "Android Engineer",
      "iOS Engineer",
      "Platform Engineer",
      "Mobile Engineer",
      "Software Engineer",
      "Engineering Manager",
      "Security Engineer",
    ],
  },
  {
    name: "Product",
    slug: "product",
    weight: 6,
    titles: [
      "Product Manager",
      "Technical Product Manager",
      "Group Product Manager",
      "Product Analyst",
      "Growth Product Manager",
    ],
  },
  {
    name: "Design",
    slug: "design",
    weight: 5,
    titles: [
      "Product Designer",
      "UX Designer",
      "UX Researcher",
      "Visual Designer",
      "Design Systems Designer",
      "Brand Designer",
    ],
  },
  {
    name: "Data",
    slug: "data",
    weight: 5,
    titles: [
      "Data Engineer",
      "Data Analyst",
      "Analytics Engineer",
      "Business Intelligence Analyst",
      "Data Scientist",
    ],
  },
  {
    name: "AI/ML",
    slug: "ai-ml",
    weight: 5,
    titles: [
      "Machine Learning Engineer",
      "Applied Scientist",
      "Research Engineer",
      "MLOps Engineer",
      "NLP Engineer",
      "Computer Vision Engineer",
    ],
  },
  {
    name: "Sales",
    slug: "sales",
    weight: 7,
    titles: [
      "Account Executive",
      "Sales Development Representative",
      "Enterprise Sales Manager",
      "Inside Sales Executive",
      "Sales Operations Analyst",
      "Partnerships Manager",
    ],
  },
  {
    name: "Marketing",
    slug: "marketing",
    weight: 5,
    titles: [
      "Performance Marketing Manager",
      "Content Marketer",
      "Brand Marketing Manager",
      "SEO Specialist",
      "Lifecycle Marketing Manager",
      "Social Media Manager",
    ],
  },
  {
    name: "Customer Success",
    slug: "customer-success",
    weight: 4,
    titles: [
      "Customer Success Manager",
      "Onboarding Specialist",
      "Account Manager",
      "Customer Success Operations Analyst",
    ],
  },
  {
    name: "Operations",
    slug: "operations",
    weight: 5,
    titles: [
      "Operations Manager",
      "City Operations Lead",
      "Supply Chain Analyst",
      "Business Operations Manager",
      "Category Manager",
    ],
  },
  {
    name: "Finance",
    slug: "finance",
    weight: 3,
    titles: [
      "Financial Analyst",
      "Accounts Manager",
      "Controller",
      "FP&A Manager",
      "Treasury Analyst",
    ],
  },
  {
    name: "People",
    slug: "people",
    weight: 3,
    titles: [
      "Technical Recruiter",
      "HR Business Partner",
      "People Operations Manager",
      "Talent Acquisition Specialist",
      "Learning and Development Manager",
    ],
  },
  {
    name: "Legal",
    slug: "legal",
    weight: 1,
    titles: ["Legal Counsel", "Compliance Manager", "Contracts Manager"],
  },
  {
    name: "Support",
    slug: "support",
    weight: 4,
    titles: [
      "Customer Support Executive",
      "Technical Support Engineer",
      "Support Operations Analyst",
      "Escalations Specialist",
    ],
  },
  {
    name: "QA",
    slug: "qa",
    weight: 4,
    titles: [
      "QA Engineer",
      "Automation Test Engineer",
      "SDET",
      "Performance Test Engineer",
      "QA Analyst",
    ],
  },
  {
    name: "DevOps",
    slug: "devops",
    weight: 3,
    titles: [
      "DevOps Engineer",
      "Site Reliability Engineer",
      "Infrastructure Engineer",
      "Cloud Engineer",
      "Build and Release Engineer",
    ],
  },
];

export const INVESTORS: readonly string[] = [
  "Peak XV Partners",
  "Accel",
  "Y Combinator",
  "Tiger Global",
  "Blume Ventures",
  "Elevation Capital",
  "Lightspeed India",
  "Z47",
  "Nexus Venture Partners",
  "3one4 Capital",
  "SoftBank Vision Fund",
  "Prosus Ventures",
  "General Catalyst",
  "Kalaari Capital",
  "Chiratae Ventures",
  "Bessemer Venture Partners",
  "Steadview Capital",
  "Sofina",
  "Alpha Wave Global",
  "Ribbit Capital",
  "Insight Partners",
  "Coatue",
  "DST Global",
  "Temasek",
  "GIC",
  "Qatar Investment Authority",
  "Norwest Venture Partners",
  "Jungle Ventures",
  "Info Edge Ventures",
  "Trifecta Capital",
  "Stellaris Venture Partners",
  "Together Fund",
  "Antler India",
  "Better Capital",
  "India Quotient",
  "Fireside Ventures",
  "Avataar Ventures",
  "WestBridge Capital",
  "A91 Partners",
  "Iron Pillar",
];

export const INDUSTRIES: readonly string[] = [
  "Fintech",
  "SaaS",
  "E-commerce",
  "Logistics",
  "Healthtech",
  "Edtech",
  "Consumer",
  "Marketplace",
  "Developer Tools",
  "AI",
  "Mobility",
  "D2C",
  "Enterprise Software",
  "Gaming",
  "Agritech",
  "Insurtech",
  "Cybersecurity",
  "Climate",
];

/* Name parts for the fictional fill companies and their founders. */
export const FILL_NAME_PREFIXES: readonly string[] = [
  "Setu",
  "Vega",
  "Nimbus",
  "Arka",
  "Tarang",
  "Kavach",
  "Prayog",
  "Bindu",
  "Chakra",
  "Dhara",
  "Ekaant",
  "Gati",
  "Hansa",
  "Indra",
  "Jyoti",
  "Kalpa",
  "Lakshya",
  "Mudra",
  "Neel",
  "Ojas",
  "Pravah",
  "Rekha",
  "Saral",
  "Tattva",
  "Udaan",
  "Varsha",
  "Yukti",
  "Zaraa",
  "Anant",
  "Bhoomi",
];

export const FILL_NAME_SUFFIXES: readonly string[] = [
  "Labs",
  "Systems",
  "Works",
  "Technologies",
  "Cloud",
  "Analytics",
  "Networks",
  "Health",
  "Money",
  "Logistics",
  "Commerce",
  "AI",
  "Studio",
  "Stack",
  "Grid",
  "Mobility",
];

export const FOUNDER_FIRST_NAMES: readonly string[] = [
  "Aarav",
  "Ananya",
  "Rohan",
  "Ishita",
  "Karthik",
  "Meera",
  "Siddharth",
  "Divya",
  "Arjun",
  "Nandini",
  "Vikram",
  "Priya",
  "Rahul",
  "Sneha",
  "Aditya",
  "Kavya",
  "Nikhil",
  "Tanvi",
  "Varun",
  "Ritika",
  "Manav",
  "Shruti",
  "Aniket",
  "Pooja",
  "Harsh",
  "Aditi",
  "Rajat",
  "Neha",
  "Gautam",
  "Swara",
];

export const FOUNDER_LAST_NAMES: readonly string[] = [
  "Sharma",
  "Iyer",
  "Reddy",
  "Nair",
  "Gupta",
  "Menon",
  "Rao",
  "Kulkarni",
  "Bhatt",
  "Chatterjee",
  "Desai",
  "Joshi",
  "Malhotra",
  "Pillai",
  "Sinha",
  "Verma",
  "Shetty",
  "Banerjee",
  "Kapoor",
  "Deshpande",
];

export const FOUNDER_TITLES: readonly string[] = [
  "Co-founder & CEO",
  "Co-founder & CTO",
  "Co-founder & COO",
  "Co-founder",
  "Co-founder & CPO",
];

/* The database enum decides the values, so the two can never drift. */
export const SENIORITIES: readonly Seniority[] = ["ENTRY", "MID", "SENIOR", "LEAD"];

/*
  Title prefixes per seniority. Mid-level roles carry no prefix, which is how
  job boards actually read.
*/
export const SENIORITY_PREFIXES: Record<Seniority, readonly string[]> = {
  ENTRY: ["Associate ", "Junior "],
  MID: [""],
  SENIOR: ["Senior "],
  LEAD: ["Lead ", "Staff ", "Principal "],
};

/* Annual INR bands before the funding-stage multiplier is applied. */
export const SALARY_BANDS: Record<Seniority, { min: number; max: number }> = {
  ENTRY: { min: 800_000, max: 1_500_000 },
  MID: { min: 1_500_000, max: 3_000_000 },
  SENIOR: { min: 3_000_000, max: 6_000_000 },
  LEAD: { min: 6_000_000, max: 9_000_000 },
};

/*
  Skills shown as chips on a job card. Every title gets two or three that a
  real posting for it would definitely list, and the rest are drawn from the
  department pool below — so two Backend Engineer roles overlap without being
  identical.
*/
export const TITLE_SKILLS: Record<string, readonly string[]> = {
  // Engineering
  "Backend Engineer": ["Node.js", "PostgreSQL", "REST APIs"],
  "Frontend Engineer": ["React", "TypeScript", "CSS"],
  "Full Stack Engineer": ["React", "Node.js", "PostgreSQL"],
  "Android Engineer": ["Kotlin", "Jetpack Compose"],
  "iOS Engineer": ["Swift", "SwiftUI"],
  "Platform Engineer": ["Kubernetes", "Go", "Distributed Systems"],
  "Mobile Engineer": ["React Native", "Kotlin"],
  "Software Engineer": ["Data Structures", "System Design"],
  "Engineering Manager": ["People Management", "Hiring"],
  "Security Engineer": ["Application Security", "Threat Modelling"],
  // Product
  "Product Manager": ["Roadmapping", "User Research"],
  "Technical Product Manager": ["API Design", "Roadmapping"],
  "Group Product Manager": ["Product Strategy", "Team Leadership"],
  "Product Analyst": ["SQL", "Amplitude"],
  "Growth Product Manager": ["Experimentation", "Funnel Analysis"],
  // Design
  "Product Designer": ["Figma", "Interaction Design"],
  "UX Designer": ["Figma", "Wireframing"],
  "UX Researcher": ["User Interviews", "Usability Testing"],
  "Visual Designer": ["Figma", "Visual Design"],
  "Design Systems Designer": ["Design Systems", "Figma"],
  "Brand Designer": ["Brand Identity", "Illustration"],
  // Data
  "Data Engineer": ["Python", "Airflow", "SQL"],
  "Data Analyst": ["SQL", "Excel"],
  "Analytics Engineer": ["dbt", "SQL"],
  "Business Intelligence Analyst": ["Power BI", "SQL"],
  "Data Scientist": ["Python", "Statistics", "SQL"],
  // AI/ML
  "Machine Learning Engineer": ["Python", "PyTorch"],
  "Applied Scientist": ["Python", "Applied Research"],
  "Research Engineer": ["Python", "PyTorch"],
  "MLOps Engineer": ["MLOps", "Kubernetes"],
  "NLP Engineer": ["NLP", "Transformers"],
  "Computer Vision Engineer": ["Computer Vision", "OpenCV"],
  // Sales
  "Account Executive": ["B2B Sales", "Negotiation"],
  "Sales Development Representative": ["Cold Outreach", "Lead Qualification"],
  "Enterprise Sales Manager": ["Enterprise Sales", "Account Planning"],
  "Inside Sales Executive": ["Inside Sales", "CRM Hygiene"],
  "Sales Operations Analyst": ["Salesforce", "Forecasting"],
  "Partnerships Manager": ["Partnerships", "Negotiation"],
  // Marketing
  "Performance Marketing Manager": ["Google Ads", "Meta Ads"],
  "Content Marketer": ["Content Strategy", "Copywriting"],
  "Brand Marketing Manager": ["Brand Positioning", "Campaign Management"],
  "SEO Specialist": ["SEO", "Keyword Research"],
  "Lifecycle Marketing Manager": ["Email Marketing", "Marketing Automation"],
  "Social Media Manager": ["Social Media", "Community Management"],
  // Customer Success
  "Customer Success Manager": ["Account Management", "Churn Reduction"],
  "Onboarding Specialist": ["Onboarding", "Customer Communication"],
  "Account Manager": ["Account Management", "Upselling"],
  "Customer Success Operations Analyst": ["CRM", "SQL"],
  // Operations
  "Operations Manager": ["Process Design", "Stakeholder Management"],
  "City Operations Lead": ["Field Operations", "P&L Ownership"],
  "Supply Chain Analyst": ["Supply Chain", "Excel"],
  "Business Operations Manager": ["Process Design", "SQL"],
  "Category Manager": ["Category Management", "Vendor Management"],
  // Finance
  "Financial Analyst": ["Financial Modelling", "Excel"],
  "Accounts Manager": ["Accounting", "Tally"],
  Controller: ["Accounting", "Audit"],
  "FP&A Manager": ["FP&A", "Financial Modelling"],
  "Treasury Analyst": ["Cash Flow Management", "Excel"],
  // People
  "Technical Recruiter": ["Sourcing", "Interviewing"],
  "HR Business Partner": ["Performance Management", "Employee Relations"],
  "People Operations Manager": ["HRIS", "Onboarding"],
  "Talent Acquisition Specialist": ["Recruiting", "Sourcing"],
  "Learning and Development Manager": ["Learning Design", "Facilitation"],
  // Legal
  "Legal Counsel": ["Commercial Contracts", "Regulatory Compliance"],
  "Compliance Manager": ["Regulatory Compliance", "Risk Assessment"],
  "Contracts Manager": ["Contract Drafting", "Negotiation"],
  // Support
  "Customer Support Executive": ["Zendesk", "Customer Communication"],
  "Technical Support Engineer": ["Troubleshooting", "SQL"],
  "Support Operations Analyst": ["SLA Management", "Ticket Triage"],
  "Escalations Specialist": ["Escalation Handling", "Root Cause Analysis"],
  // QA
  "QA Engineer": ["Manual Testing", "Test Planning"],
  "Automation Test Engineer": ["Selenium", "Test Automation"],
  SDET: ["Test Automation", "Java"],
  "Performance Test Engineer": ["JMeter", "Load Testing"],
  "QA Analyst": ["Test Cases", "Bug Triage"],
  // DevOps
  "DevOps Engineer": ["Docker", "CI/CD"],
  "Site Reliability Engineer": ["Kubernetes", "Incident Response"],
  "Infrastructure Engineer": ["Terraform", "Linux"],
  "Cloud Engineer": ["AWS", "Terraform"],
  "Build and Release Engineer": ["Jenkins", "CI/CD"],
};

/* Keyed by department slug. Padding for the title skills above. */
export const DEPARTMENT_SKILLS: Record<string, readonly string[]> = {
  engineering: [
    "TypeScript",
    "Python",
    "Java",
    "Go",
    "Redis",
    "Kafka",
    "AWS",
    "System Design",
    "Docker",
    "Git",
  ],
  product: [
    "SQL",
    "A/B Testing",
    "User Research",
    "Roadmapping",
    "Figma",
    "Analytics",
    "Stakeholder Management",
    "PRD Writing",
  ],
  design: [
    "Figma",
    "Prototyping",
    "Design Systems",
    "User Research",
    "Accessibility",
    "Motion Design",
    "Wireframing",
    "Visual Design",
  ],
  data: [
    "SQL",
    "Python",
    "dbt",
    "Airflow",
    "Snowflake",
    "Spark",
    "Looker",
    "Data Modelling",
    "ETL",
  ],
  "ai-ml": [
    "Python",
    "PyTorch",
    "TensorFlow",
    "MLOps",
    "LLMs",
    "Feature Engineering",
    "Model Deployment",
    "Hugging Face",
    "Vector Databases",
  ],
  sales: [
    "B2B Sales",
    "Pipeline Management",
    "Salesforce",
    "Negotiation",
    "Account Planning",
    "Forecasting",
    "Lead Qualification",
    "HubSpot",
  ],
  marketing: [
    "SEO",
    "Content Strategy",
    "Google Ads",
    "Marketing Automation",
    "Copywriting",
    "Analytics",
    "Email Marketing",
    "Brand Positioning",
  ],
  "customer-success": [
    "Onboarding",
    "Account Management",
    "Churn Reduction",
    "CRM",
    "Escalation Handling",
    "Upselling",
    "Customer Advocacy",
    "QBRs",
  ],
  operations: [
    "Process Design",
    "Excel",
    "SQL",
    "Vendor Management",
    "Supply Chain",
    "SOP Design",
    "Capacity Planning",
    "Stakeholder Management",
  ],
  finance: [
    "Financial Modelling",
    "Excel",
    "Accounting",
    "GST Compliance",
    "FP&A",
    "Audit",
    "Variance Analysis",
    "Cash Flow Management",
  ],
  people: [
    "Recruiting",
    "Sourcing",
    "HRIS",
    "Employer Branding",
    "Interviewing",
    "Onboarding",
    "Performance Management",
    "Compensation Benchmarking",
  ],
  legal: [
    "Contract Drafting",
    "Commercial Contracts",
    "Regulatory Compliance",
    "Data Privacy",
    "Corporate Governance",
    "DPDP Act",
    "Risk Assessment",
  ],
  support: [
    "Zendesk",
    "Freshdesk",
    "Troubleshooting",
    "SLA Management",
    "Ticket Triage",
    "Customer Communication",
    "Documentation",
  ],
  qa: [
    "Test Automation",
    "Selenium",
    "Cypress",
    "API Testing",
    "Postman",
    "Regression Testing",
    "Test Planning",
    "Appium",
  ],
  devops: [
    "Kubernetes",
    "Docker",
    "Terraform",
    "AWS",
    "CI/CD",
    "Linux",
    "Prometheus",
    "Grafana",
    "Ansible",
  ],
};

/*
  How a company sells, which is a different question from what it sells.
  Anchors carry hand-written tags; the fictional companies borrow theirs from
  their industries so a "Marketplace" company never reads as pure SaaS.
*/
export const BUSINESS_MODELS = ["B2B", "B2C", "D2C", "Marketplace", "SaaS"] as const;

export const BUSINESS_MODEL_BY_INDUSTRY: Record<string, readonly string[]> = {
  Fintech: ["B2C"],
  SaaS: ["B2B", "SaaS"],
  "E-commerce": ["B2C", "Marketplace"],
  Logistics: ["B2B"],
  Healthtech: ["B2C"],
  Edtech: ["B2C"],
  Consumer: ["B2C"],
  Marketplace: ["Marketplace"],
  "Developer Tools": ["B2B", "SaaS"],
  AI: ["B2B"],
  Mobility: ["B2C"],
  D2C: ["D2C", "B2C"],
  "Enterprise Software": ["B2B", "SaaS"],
  Gaming: ["B2C"],
  Agritech: ["B2B"],
  Insurtech: ["B2C"],
  Cybersecurity: ["B2B", "SaaS"],
  Climate: ["B2B"],
};
