/*
  One shows per day, picked by day of year. Written for this project — short,
  a little wry, nothing borrowed.
*/
export const QUOTES = [
  "The best roles are rarely the loudest ones.",
  "Every company was once three people and a rented desk.",
  "A commute you enjoy is a raise you did not negotiate.",
  "Read the founders before you read the perks.",
  "Small teams move fast. Small teams also notice.",
  "The job you can explain to your family is not always the right one.",
  "Ask what broke last quarter, not what launched.",
  "A map is just a list that respects your time.",
  "Funding is a starting gun, not a finish line.",
  "The interview goes both ways, even when it does not feel like it.",
  "Pick the problem first. The title follows.",
  "Nobody remembers the job description. Everybody remembers the manager.",
  "Remote is a place too. It just has better coffee.",
  "The role that scares you slightly is usually the one.",
  "A good team will tell you what they are bad at.",
  "Compensation is a number. Compounding is a decision.",
  "You can learn a stack. You cannot learn a culture from outside.",
  "Two years somewhere real beats six months in five places.",
  "Look for companies that ship on Fridays and sleep fine.",
  "Curiosity travels better than any framework.",
  "The quiet company down the road might be the one hiring.",
  "Ask who left recently, and why they say they left.",
  "A startup is a promise with a payroll.",
  "Choose colleagues you would want to be wrong in front of.",
  "The market is noisy. Your shortlist does not have to be.",
  "Enthusiasm is not a substitute for scope.",
  "Every map has a corner nobody has walked yet.",
  "Say no to the tenth-best option so you can hear the first.",
  "Growth is a side effect of good problems.",
  "The right commute is the one you would happily make daily.",
];
